insert into cage.raw (id,species,
lastUpload,name,org,publication) values(uuid(), 'human',
 '2016-1-21 22:10', 'mike', 'tongji', 'Nat Method');

insert into cage.raw (id,species,
lastUpload,name,org,publication) values(uuid(), 'human',
 '2016-1-22 22:10', 'john', 'tongji', 'Nat Biotech');

insert into cage.raw (id,species,
lastUpload,name,org,publication) values(uuid(), 'mouse',
 '2016-1-23 22:10', 'mary', 'tongji', '');
